---
title       : re\:teatteri
subtitle    : 
author      : 
job         : 
framework   : revealjs        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

# re:teatteri
### slides

<small> for [@safkame](https://instagram.com/safka.me/) </small>

---&vertical

## 1: KA
### 1. Motti
<small>[Google](http://www.google.com/search?q=Motti+ravintola)</small>


***

## 1: JU
### 2. Kynsilaukka
<small>[Google](http://www.google.com/search?q=Kynsilaukka+ravintola)</small>


***

## 1: HE
### 3. Gastone
<small>[Google](http://www.google.com/search?q=Gastone+ravintola)</small>


***

## 1: MI
### 4. Villetta
<small>[Google](http://www.google.com/search?q=Villetta+ravintola)</small>


***

## 1: LA
### 5. Len's Keishoku & Bar
<small>[Google](http://www.google.com/search?q=Len's Keishoku & Bar+ravintola)</small>


***

## 1: MA
### 6. Sea Horse
<small>[Google](http://www.google.com/search?q=Sea Horse+ravintola)</small>


***

## 1: JA
### 7. Messenius
<small>[Google](http://www.google.com/search?q=Messenius+ravintola)</small>


***

## 2: KA
### 8. Hariton
<small>[Google](http://www.google.com/search?q=Hariton+ravintola)</small>


***

## 2: JU
### 9. G18
<small>[Google](http://www.google.com/search?q=G18+ravintola)</small>


***

## 2: MA
### 10. Suomi Lautasella
<small>[Google](http://www.google.com/search?q=Suomi Lautasella+ravintola)</small>


***

## 2: HE
### 11. Graniittilinna
<small>[Google](http://www.google.com/search?q=Graniittilinna+ravintola)</small>


***

## 2: LA
### 12. Rodolfo
<small>[Google](http://www.google.com/search?q=Rodolfo+ravintola)</small>


***

## 2: MI
### 13. Kuu
<small>[Google](http://www.google.com/search?q=Kuu+ravintola)</small>


***

## 2: HE
### 14. La Bodega
<small>[Google](http://www.google.com/search?q=La Bodega+ravintola)</small>


***

## 2: JA
### 15. Bar Teos
<small>[Google](http://www.google.com/search?q=Bar Teos+ravintola)</small>


***

## 3: KA
### 16. Cella
<small>[Google](http://www.google.com/search?q=Cella+ravintola)</small>


***

## 3: JU
### 17. Kuurna
<small>[Google](http://www.google.com/search?q=Kuurna+ravintola)</small>


***

## 3: JA
### 18. Weeruska
<small>[Google](http://www.google.com/search?q=Weeruska+ravintola)</small>


***

## 3: MA
### 19. Casaro
<small>[Google](http://www.google.com/search?q=Casaro+ravintola)</small>


***

## 3: LA
### 20. BBQ House
<small>[Google](http://www.google.com/search?q=BBQ House+ravintola)</small>


***

## 3: MI
### 21. Zinnkeller
<small>[Google](http://www.google.com/search?q=Zinnkeller+ravintola)</small>


***

## 4: JU
### 22. Farouge
<small>[Google](http://www.google.com/search?q=Farouge+ravintola)</small>


***

## 4: JA
### 23. Pannonia
<small>[Google](http://www.google.com/search?q=Pannonia+ravintola)</small>


***

## 4: MA
### 24. Korea House
<small>[Google](http://www.google.com/search?q=Korea House+ravintola)</small>


***

## 4: KA
### 25. Basilica
<small>[Google](http://www.google.com/search?q=Basilica+ravintola)</small>


***

## 4: MI
### 26. Juuri
<small>[Google](http://www.google.com/search?q=Juuri+ravintola)</small>


***

## 4: HE
### 27. Persilja
<small>[Google](http://www.google.com/search?q=Persilja+ravintola)</small>


***

## 4: LA
### 28. Villa Thai
<small>[Google](http://www.google.com/search?q=Villa Thai+ravintola)</small>


***

## 5: KA
### 29. kosmos
<small>[Google](http://www.google.com/search?q=kosmos+ravintola)</small>


***

## 5: JU
### 30. teatteri
<small>[Google](http://www.google.com/search?q=teatteri+ravintola)</small>


***

## 5: MA
### 31. kabuki
<small>[Google](http://www.google.com/search?q=kabuki+ravintola)</small>


***

## 5: MI
### 32. maxill
<small>[Google](http://www.google.com/search?q=maxill+ravintola)</small>


***

## 5: LA
### 33. mestaritalli
<small>[Google](http://www.google.com/search?q=mestaritalli+ravintola)</small>


***

## 5: JA
### 34. elite
<small>[Google](http://www.google.com/search?q=elite+ravintola)</small>


***

## 5: HE
### 35. ateljee
<small>[Google](http://www.google.com/search?q=ateljee+ravintola)</small>


***

## 6: HE
### 36. jailbird
<small>[Google](http://www.google.com/search?q=jailbird+ravintola)</small>


***

## 6: KA
### 37. safka
<small>[Google](http://www.google.com/search?q=safka+ravintola)</small>


***

## 6: JU
### 38. grotesk
<small>[Google](http://www.google.com/search?q=grotesk+ravintola)</small>


***

## 6: JA
### 39. Benjam's bistro
<small>[Google](http://www.google.com/search?q=Benjam's bistro+ravintola)</small>


***

## 6: LA
### 40. Rymy eetu
<small>[Google](http://www.google.com/search?q=Rymy eetu+ravintola)</small>


***

## 6: MI
### 41. Karl Johan
<small>[Google](http://www.google.com/search?q=Karl Johan+ravintola)</small>


***

## 6: MA
### 42. Kellarikrouvi
<small>[Google](http://www.google.com/search?q=Kellarikrouvi+ravintola)</small>


***

## 7: HE
### 43. La Societe Du Cochon
<small>[Google](http://www.google.com/search?q=La Societe Du Cochon+ravintola)</small>


***

## 7: JU
### 44. Helmi
<small>[Google](http://www.google.com/search?q=Helmi+ravintola)</small>


***

## 7: KA
### 45. Coma
<small>[Google](http://www.google.com/search?q=Coma+ravintola)</small>


***

## 7: JA
### 46. Macu
<small>[Google](http://www.google.com/search?q=Macu+ravintola)</small>


***

## 7: MA
### 47. Konstan möljä
<small>[Google](http://www.google.com/search?q=Konstan möljä+ravintola)</small>


***

## 7: LA
### 48. Trenta
<small>[Google](http://www.google.com/search?q=Trenta+ravintola)</small>


***

## 7: MI
### 49. Holvari
<small>[Google](http://www.google.com/search?q=Holvari+ravintola)</small>


***

## 8: JU
### 50. del mar
<small>[Google](http://www.google.com/search?q=del mar+ravintola)</small>


***

## 8: KA
### 51. Raku ya
<small>[Google](http://www.google.com/search?q=Raku ya+ravintola)</small>


***

## 8: HE
### 52. Troikka
<small>[Google](http://www.google.com/search?q=Troikka+ravintola)</small>


***

## 8: JA
### 53. Storyville
<small>[Google](http://www.google.com/search?q=Storyville+ravintola)</small>


***

## 8: MI
### 54. Kilim
<small>[Google](http://www.google.com/search?q=Kilim+ravintola)</small>


***

## 8: MA
### 55. Elviira
<small>[Google](http://www.google.com/search?q=Elviira+ravintola)</small>


***

## 8: LA
### 56. Parilla espanola
<small>[Google](http://www.google.com/search?q=Parilla espanola+ravintola)</small>


***

## 9: JA
### 57. Azoros
<small>[Google](http://www.google.com/search?q=Azoros+ravintola)</small>


***

## 9: HE
### 58. Virgin oil co
<small>[Google](http://www.google.com/search?q=Virgin oil co+ravintola)</small>


***

## 9: JU
### 59. Fishmarket
<small>[Google](http://www.google.com/search?q=Fishmarket+ravintola)</small>


***

## 9: KA
### 60. Mecca
<small>[Google](http://www.google.com/search?q=Mecca+ravintola)</small>


***

## 9: MA
### 61. La Medina
<small>[Google](http://www.google.com/search?q=La Medina+ravintola)</small>


***

## 9: LA
### 62. Pirate
<small>[Google](http://www.google.com/search?q=Pirate+ravintola)</small>


***

## 9: MI
### 63. Brunos
<small>[Google](http://www.google.com/search?q=Brunos+ravintola)</small>


---&vertical

## 10: MA (1)
### 68. Bistro Helsinki 15, Points: 86
<small>[Google](http://www.google.com/search?q=Bistro Helsinki 15+ravintola)</small>


***

## 10: KA (2)
### 67. Farang, Points: 67
<small>[Google](http://www.google.com/search?q=Farang+ravintola)</small>


***

## 10: LA (3)
### 69. Strindberg, Points: 59
<small>[Google](http://www.google.com/search?q=Strindberg+ravintola)</small>


***

## 10: JU (4)
### 64. Aito, Points: 57
<small>[Google](http://www.google.com/search?q=Aito+ravintola)</small>


***

## 10: HE (5)
### 66. Luomo, Points: 42
<small>[Google](http://www.google.com/search?q=Luomo+ravintola)</small>


***

## 10: JA (6)
### 65. Töölönranta, Points: 24
<small>[Google](http://www.google.com/search?q=Töölönranta+ravintola)</small>


***

## 10: MI (7)
### 70. Vaelsa, Points: 16
<small>[Google](http://www.google.com/search?q=Vaelsa+ravintola)</small>


---&vertical

## 11: JA (1)
### 71. Lasipalatsi, Points: 74
<small>[Google](http://www.google.com/search?q=Lasipalatsi+ravintola)</small>


***

## 11: MA (2)
### 77. Bistro Leon, Points: 68
<small>[Google](http://www.google.com/search?q=Bistro Leon+ravintola)</small>


***

## 11: JU (3)
### 76. Solna, Points: 68
<small>[Google](http://www.google.com/search?q=Solna+ravintola)</small>


***

## 11: MI (4)
### 74. Carelia, Points: 49
<small>[Google](http://www.google.com/search?q=Carelia+ravintola)</small>


***

## 11: LA (5)
### 75. Olive's, Points: 46
<small>[Google](http://www.google.com/search?q=Olive's+ravintola)</small>


***

## 11: HE (6)
### 72. Grilli it, Points: 22
<small>[Google](http://www.google.com/search?q=Grilli it+ravintola)</small>


***

## 11: KA (7)
### 73. Martta, Points: 18
<small>[Google](http://www.google.com/search?q=Martta+ravintola)</small>


---&vertical

## 12: JU (1)
### 79. Tokyo 55, Points: 88
<small>[Google](http://www.google.com/search?q=Tokyo 55+ravintola)</small>


***

## 12: MI (2)
### 84. Backfickan, Points: 69
<small>[Google](http://www.google.com/search?q=Backfickan+ravintola)</small>


***

## 12: JA (3)
### 80. Mange sud, Points: 64
<small>[Google](http://www.google.com/search?q=Mange sud+ravintola)</small>


***

## 12: MA (4)
### 83. la table, Points: 55
<small>[Google](http://www.google.com/search?q=la table+ravintola)</small>


***

## 12: KA (5)
### 78. Ravintola Savu, Points: 38
<small>[Google](http://www.google.com/search?q=Ravintola Savu+ravintola)</small>


***

## 12: HE (6)
### 81. Zio Pepe, Points: 24
<small>[Google](http://www.google.com/search?q=Zio Pepe+ravintola)</small>


***

## 12: LA (7)
### 82. Tang dynasty, Points: 3
<small>[Google](http://www.google.com/search?q=Tang dynasty+ravintola)</small>


---&vertical

## 13: JU (1)
### 88. Goce, Points: 63
<small>[Google](http://www.google.com/search?q=Goce+ravintola)</small>


***

## 13: KA (2)
### 89. Kolme kruunua, Points: 62
<small>[Google](http://www.google.com/search?q=Kolme kruunua+ravintola)</small>


***

## 13: MI (3)
### 90. Perho, Points: 58
<small>[Google](http://www.google.com/search?q=Perho+ravintola)</small>


***

## 13: MA (4)
### 86. Stone's, Points: 48
<small>[Google](http://www.google.com/search?q=Stone's+ravintola)</small>


***

## 13: HE (5)
### 87. Eeron keittiö, Points: 48
<small>[Google](http://www.google.com/search?q=Eeron keittiö+ravintola)</small>


***

## 13: LA (6)
### 91. Umeshu, Points: 30
<small>[Google](http://www.google.com/search?q=Umeshu+ravintola)</small>


***

## 13: JA (7)
### 85. Aleksandria, Points: 26
<small>[Google](http://www.google.com/search?q=Aleksandria+ravintola)</small>


---&vertical

## 14: MI (1)
### 94. Lupolo, Points: 94
<small>[Google](http://www.google.com/search?q=Lupolo+ravintola)</small>


***

## 14: HE (2)
### 92. König, Points: 71
<small>[Google](http://www.google.com/search?q=König+ravintola)</small>


***

## 14: LA (3)
### 96. Alia, Points: 71
<small>[Google](http://www.google.com/search?q=Alia+ravintola)</small>


***

## 14: KA (4)
### 98. Chef & Sommelier, Points: 43
<small>[Google](http://www.google.com/search?q=Chef & Sommelier+ravintola)</small>


***

## 14: MA (5)
### 97. Sunn, Points: 36
<small>[Google](http://www.google.com/search?q=Sunn+ravintola)</small>


***

## 14: JU (6)
### 95. Gaijin, Points: 29
<small>[Google](http://www.google.com/search?q=Gaijin+ravintola)</small>


***

## 14: JA (7)
### 93. Johannes, Points: 7
<small>[Google](http://www.google.com/search?q=Johannes+ravintola)</small>


---&vertical

## 15: JU (1)
### 100. Koiton Grilli, Points: 92
<small>[Google](http://www.google.com/search?q=Koiton Grilli+ravintola)</small>


***

## 15: KA (2)
### 102. Motti, Points: 71
<small>[Google](http://www.google.com/search?q=Motti+ravintola)</small>


***

## 15: MA (3)
### 103. Shanghai Cowboy , Points: 58
<small>[Google](http://www.google.com/search?q=Shanghai Cowboy +ravintola)</small>


***

## 15: LA (4)
### 101. Glöd, Points: 50
<small>[Google](http://www.google.com/search?q=Glöd+ravintola)</small>


***

## 15: JA (5)
### 105. Nuevo, Points: 26
<small>[Google](http://www.google.com/search?q=Nuevo+ravintola)</small>


***

## 15: HE (6)
### 104. Funky Burger, Points: 22
<small>[Google](http://www.google.com/search?q=Funky Burger+ravintola)</small>


***

## 15: MI (7)
### 99. Soul kitchen, Points: 11
<small>[Google](http://www.google.com/search?q=Soul kitchen+ravintola)</small>


---&vertical

## 16: KA (1)
### 106. Spis, Points: 96
<small>[Google](http://www.google.com/search?q=Spis+ravintola)</small>


***

## 16: MA (2)
### 109. Namu, Points: 84
<small>[Google](http://www.google.com/search?q=Namu+ravintola)</small>


***

## 16: JA (3)
### 108. Strindberg, Points: 60
<small>[Google](http://www.google.com/search?q=Strindberg+ravintola)</small>


***

## 16: MI (4)
### 110. Hoshitos, Points: 53
<small>[Google](http://www.google.com/search?q=Hoshitos+ravintola)</small>


***

## 16: LA (5)
### 107. Patrona, Points: 32
<small>[Google](http://www.google.com/search?q=Patrona+ravintola)</small>


***

## 16: HE (6)
### 112. Sipuli, Points: 32
<small>[Google](http://www.google.com/search?q=Sipuli+ravintola)</small>


***

## 16: JU (7)
### 111. Kunigatar Saba, Points: 7
<small>[Google](http://www.google.com/search?q=Kunigatar Saba+ravintola)</small>


---&vertical

## 17: JA (1)
### 113. Meche, Points: 94
<small>[Google](http://www.google.com/search?q=Meche+ravintola)</small>


***

## 17: MA (2)
### 117. Kitchen & Co, Points: 75
<small>[Google](http://www.google.com/search?q=Kitchen & Co+ravintola)</small>


***

## 17: HE (3)
### 116. Il Bucatino, Points: 71
<small>[Google](http://www.google.com/search?q=Il Bucatino+ravintola)</small>


***

## 17: KA (4)
### 114. Kolo, Points: 57
<small>[Google](http://www.google.com/search?q=Kolo+ravintola)</small>


***

## 17: MI (5)
### 118. Paksu, Points: 35
<small>[Google](http://www.google.com/search?q=Paksu+ravintola)</small>


***

## 17: JU (6)
### 115. Flada, Points: 26
<small>[Google](http://www.google.com/search?q=Flada+ravintola)</small>


***

## 17: LA (7)
### 119. hard rock cafe, Points: 23
<small>[Google](http://www.google.com/search?q=hard rock cafe+ravintola)</small>


---&vertical

## 18: MI (1)
### 126. Krog Madame, Points: 86
<small>[Google](http://www.google.com/search?q=Krog Madame+ravintola)</small>


***

## 18: KA (2)
### 121. Ask, Points: 62
<small>[Google](http://www.google.com/search?q=Ask+ravintola)</small>


***

## 18: JA (3)
### 120. Nokka, Points: 56
<small>[Google](http://www.google.com/search?q=Nokka+ravintola)</small>


***

## 18: LA (4)
### 125. Boulevard social, Points: 50
<small>[Google](http://www.google.com/search?q=Boulevard social+ravintola)</small>


***

## 18: MA (5)
### 122. PureBistro, Points: 38
<small>[Google](http://www.google.com/search?q=PureBistro+ravintola)</small>


***

## 18: JU (6)
### 124. Glogatan 4, Points: 31
<small>[Google](http://www.google.com/search?q=Glogatan 4+ravintola)</small>


***

## 18: HE (7)
### 123. Putte's pizza, Points: 6
<small>[Google](http://www.google.com/search?q=Putte's pizza+ravintola)</small>


---&vertical

## 19: KA (1)
### 128. Hoku, Points: 89
<small>[Google](http://www.google.com/search?q=Hoku+ravintola)</small>


***

## 19: MI (2)
### 127. Chez Dominique, Points: 77
<small>[Google](http://www.google.com/search?q=Chez Dominique+ravintola)</small>


***

## 19: JU (3)
### 132. Toca, Points: 46
<small>[Google](http://www.google.com/search?q=Toca+ravintola)</small>


***

## 19: JA (4)
### 129. Bistro O'Mat, Points: 46
<small>[Google](http://www.google.com/search?q=Bistro O'Mat+ravintola)</small>


***

## 19: MA (5)
### 131. Kannas, Points: 40
<small>[Google](http://www.google.com/search?q=Kannas+ravintola)</small>


***

## 19: LA (6)
### 130. Helsinki Bruggeri, Points: 14
<small>[Google](http://www.google.com/search?q=Helsinki Bruggeri+ravintola)</small>


---&vertical

## 20: MA (1)
### 138. Lusikka, Points: 79
<small>[Google](http://www.google.com/search?q=Lusikka+ravintola)</small>


***

## 20: HE (2)
### 139. Un Cerdo Ciego - Sokea Possu, Points: 73
<small>[Google](http://www.google.com/search?q=Un Cerdo Ciego - Sokea Possu+ravintola)</small>


***

## 20: JA (3)
### 137. Pastis, Points: 55
<small>[Google](http://www.google.com/search?q=Pastis+ravintola)</small>


***

## 20: MI (4)
### 136. Aada, Points: 41
<small>[Google](http://www.google.com/search?q=Aada+ravintola)</small>


***

## 20: LA (5)
### 133. tres bones, Points: 40
<small>[Google](http://www.google.com/search?q=tres bones+ravintola)</small>


***

## 20: KA (6)
### 134. Roslund, Points: 30
<small>[Google](http://www.google.com/search?q=Roslund+ravintola)</small>


***

## 20: JU (7)
### 135. Tony's deli, Points: 21
<small>[Google](http://www.google.com/search?q=Tony's deli+ravintola)</small>


---&vertical

## 21: LA (1)
### 143. Sandro, Points: 93
<small>[Google](http://www.google.com/search?q=Sandro+ravintola)</small>


***

## 21: KA (2)
### 144. Emo, Points: 58
<small>[Google](http://www.google.com/search?q=Emo+ravintola)</small>


***

## 21: MI (3)
### 146. Rafla, Points: 57
<small>[Google](http://www.google.com/search?q=Rafla+ravintola)</small>


***

## 21: MA (4)
### 140. Brasserie Eira, Points: 48
<small>[Google](http://www.google.com/search?q=Brasserie Eira+ravintola)</small>


***

## 21: JU (5)
### 145. Bronda, Points: 40
<small>[Google](http://www.google.com/search?q=Bronda+ravintola)</small>


***

## 21: HE (6)
### 141. Trattoria Sogno, Points: 34
<small>[Google](http://www.google.com/search?q=Trattoria Sogno+ravintola)</small>


***

## 21: JA (7)
### 142. Kylä, Points: 13
<small>[Google](http://www.google.com/search?q=Kylä+ravintola)</small>


---&vertical

## 22: MA (1)
### 148. Kolmon3n, Points: 89
<small>[Google](http://www.google.com/search?q=Kolmon3n+ravintola)</small>


***

## 22: JA (2)
### 149. Savoy, Points: 75
<small>[Google](http://www.google.com/search?q=Savoy+ravintola)</small>


***

## 22: MI (3)
### 151. Ragu, Points: 61
<small>[Google](http://www.google.com/search?q=Ragu+ravintola)</small>


***

## 22: JU (4)
### 152. Pompiers, Points: 47
<small>[Google](http://www.google.com/search?q=Pompiers+ravintola)</small>


***

## 22: LA (5)
### 150. Pastor, Points: 45
<small>[Google](http://www.google.com/search?q=Pastor+ravintola)</small>


***

## 22: KA (6)
### 147. Lähiö, Points: 26
<small>[Google](http://www.google.com/search?q=Lähiö+ravintola)</small>


***

## 22: HE (7)
### 153. Woolshed, Points: 17
<small>[Google](http://www.google.com/search?q=Woolshed+ravintola)</small>


---&vertical

## 23: KA (1)
### 157. Lyon, Points: 82
<small>[Google](http://www.google.com/search?q=Lyon+ravintola)</small>


***

## 23: HE (2)
### 160. Richard von Trappe, Points: 74
<small>[Google](http://www.google.com/search?q=Richard von Trappe+ravintola)</small>


***

## 23: LA (3)
### 156. Sundsman's Krog, Points: 58
<small>[Google](http://www.google.com/search?q=Sundsman's Krog+ravintola)</small>


***

## 23: MA (4)
### 154. Sinne, Points: 51
<small>[Google](http://www.google.com/search?q=Sinne+ravintola)</small>


***

## 23: JA (5)
### 155. Lehtovaara, Points: 45
<small>[Google](http://www.google.com/search?q=Lehtovaara+ravintola)</small>


***

## 23: JU (6)
### 158. The Cock, Points: 23
<small>[Google](http://www.google.com/search?q=The Cock+ravintola)</small>


***

## 23: MI (7)
### 159. No.11, Points: 6
<small>[Google](http://www.google.com/search?q=No.11+ravintola)</small>


---&vertical

## 24: JU (1)
### 165. Regina, Points: 76
<small>[Google](http://www.google.com/search?q=Regina+ravintola)</small>


***

## 24: MA (2)
### 163. Loung3, Points: 65
<small>[Google](http://www.google.com/search?q=Loung3+ravintola)</small>


***

## 24: JA (3)
### 166. Pjazza, Points: 54
<small>[Google](http://www.google.com/search?q=Pjazza+ravintola)</small>


***

## 24: LA (4)
### 162. Meripaviljonki, Points: 46
<small>[Google](http://www.google.com/search?q=Meripaviljonki+ravintola)</small>


***

## 24: KA (5)
### 164. Hoshito Töölö, Points: 46
<small>[Google](http://www.google.com/search?q=Hoshito Töölö+ravintola)</small>


***

## 24: MI (6)
### 167. El Greco, Points: 39
<small>[Google](http://www.google.com/search?q=El Greco+ravintola)</small>


***

## 24: HE (7)
### 161. Goodwin the Steak House, Points: 21
<small>[Google](http://www.google.com/search?q=Goodwin the Steak House+ravintola)</small>


---&vertical

## 25: JU (1)
### 168. Lumiere, Points: NaN
<small>[Google](http://www.google.com/search?q=Lumiere+ravintola)</small>


